shared:
  generate-file-content-params: &gfcp
    platform: linux
    image_resource:
      type: docker-image
      source: {repository: czero/cflinuxfs2}
    inputs:
    - name: pivnet-product
    outputs:
    - name: generate-file-content
    run:
      path: bash
      args:
      - -c
      - |
        desired_version=$(jq --raw-output '.Release.Version' < ./pivnet-product/metadata.json)
        echo "$desired_version" > generate-file-content/output.txt

resource_types:
- name: pivotal-tracker-resource
  type: docker-image
  source:
    repository: aegershman/pivotal-tracker-resource
    tag: latest
    username: ((docker.username))
    password: ((docker.password))

- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: tracker
  type: pivotal-tracker-resource
  source:
    project_id: ((tracker.project_id))
    token: ((tracker.token))

- name: p-mysql
  type: pivnet
  source:
    product_slug: p-mysql
    product_version_regex: 1\.10\..*
    api_token: ((pivnet_token))
    region: us-west-2
    sort_by: semver

jobs:
- name: create-story-for-new-version-of-p-mysql
  plan:
  - get: pivnet-product
    resource: p-mysql
    trigger: true
    params: {globs: []}
  - task: generate-file-content
    config: {<<: *gfcp}
  - put: tracker
    params:
      name: DEMO. Upgrade to p-mysql $NAME_FILE in Sandbox
      name_file: generate-file-content/output.txt
      owner_ids: [3016456]
      story_type: chore
      labels:
      - name: sandbox
      - name: p-mysql
      - name: tile-upgrade

- name: start-story
  plan:
  - get: pivnet-product
    passed: [create-story-for-new-version-of-p-mysql]
    resource: p-mysql
    trigger: true
    params: {globs: []}
  - task: generate-file-content
    config: {<<: *gfcp}
  - put: tracker
    params:
      name: DEMO. Upgrade to p-mysql $NAME_FILE in Sandbox
      name_file: generate-file-content/output.txt
      current_state: started

- name: accept-story
  plan:
  - get: pivnet-product
    passed: [start-story]
    resource: p-mysql
    trigger: true
    params: {globs: []}
  - task: generate-file-content
    config: {<<: *gfcp}
  - put: tracker
    params:
      name: DEMO. Upgrade to p-mysql $NAME_FILE in Sandbox
      name_file: generate-file-content/output.txt
      current_state: accepted