resource_types:
- name: pivotal-tracker-resource
  type: docker-image
  source:
    repository: aegershman/pivotal-tracker-resource
    tag: latest
    username: ((docker.username))
    password: ((docker.password))

resources:
- name: source
  type: git
  source:
    uri: ((git.uri))
    branch: ((git.branch))
    private_key: ((git.private_key))

# - name: version
#   type: semver
#   source:
#     driver: git
#     uri: ((git.uri))
#     branch: ((semver.branch))
#     private_key: ((git.private_key))
#     file: ((semver.file))

- name: docker
  type: docker-image
  source:
    repository: ((docker.repository))
    username: ((docker.username))
    password: ((docker.password))

jobs:
- name: build-resource
  plan:
  - get: source
    trigger: true
  - put: docker
    params:
      build: source
